### ISSUE TITLE
API está ATIVA?

### ISSUE THREAD

**Issue by yagovf288** [100n0m3/API-Carros#10]
Essa API está ativa ainda? como me cadastro para poder utiliza-la?

**Comment by 100n0m3** [comment]
FAVOR CHAMAR NO TELEGRAM 44-991559009

**Comment by iconio** [comment]
@100n0m3 tudo tranquilo irmao? Eu tentei adicionar esse numero no telegram mas nao reconheceu, vc teria outro? Abraco
