### ISSUE TITLE
API retornando erro

### ISSUE THREAD

**Issue by yancorrea1995** [100n0m3/API-Carros#2]
Bom dia! Eu uso a API em um aplicativo que sempre funcionou muito bem e a mesma está retornando Internal Server Error em todas as requisições, por exemplo a consulta de placa com /json. Sabe me dizer qual o problema e se tem alguma previsão de retorno à normalidade? Obrigado!

**Comment by yuriedmundo** [comment]
Aqui está normal

**Comment by 100n0m3** [comment]
bom dia, obrigado por entrar em contato, realmente  estava fora, devido a uma migração de VPS que tem apresentado bastante problemas mas já está funcionando estamos trabalhando para que isso não ocorra mais.
