### ISSUE TITLE
BD

### ISSUE THREAD

**Issue by PyVisionlabs** [100n0m3/API-Carros#4]

**Comment by PyVisionlabs** [comment]
como faço pra ter acesso ao BD? poderia disponibiliza-lo? não consegui fazer o donwload pela API

**Comment by guidevnet** [comment]
Eu tamabém gostaria de acesso ao BD, pois estou precisando consultar uma lista de placas. A issue #1 indica que este problema ocorre desde abril.

Algum update? A consulta em lote tambem não tá rolando...

**Comment by 100n0m3** [comment]
Bom dia, sobre o download do bd esta indisponível para publico por enquanto devido a custos com servidor, sobre a consulta em lote, vou validar obrigado por avisar, caso queriam saber mais sobre o download do bd me manda um e-mail.

**Comment by guidevnet** [comment]
@100n0m3 mandei, obridado desde ja
