### ISSUE TITLE
Informações

### ISSUE THREAD

**Issue by giovanigenerali** [100n0m3/API-Carros#5]
@100n0m3 não sabia que tinham conseguido acesso a API, usei por um bom tempo mas haviam bloqueado e estava complexo para gerar o token, etc... o seu script está disponível ou tem algum custo? eu gostaria de implementar em um servidor próprio, se puder me passar mais informações, obrigado.

**Comment by 100n0m3** [comment]
Chama no zap 44-991559009

Enviada do Outlook Mobile<https://aka.ms/blhgte>

________________________________
