### ISSUE TITLE
informações

### ISSUE THREAD

**Issue by webacoes** [100n0m3/API-Carros#6]
Bom dia,

Você teria mais informações do veículo? Tal como gravames, se é de leilão?
Saberia me dizer onde consigo?

Obrigado

**Comment by 100n0m3** [comment]
Chama no zap 44-991559009

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by 100n0m3** [comment]
favor entrar em contato

**Comment by 100n0m3** [comment]
44-991559009
