### ISSUE TITLE
A api funciona?

### ISSUE THREAD

**Issue by DevMatheusMartinez** [100n0m3/API-Carros#8]
Boa tarde, gostaria saber se a API ainda funciona? Obrigado.

**Comment by 100n0m3** [comment]
opa , funciona sim o q acontece é q ela esta limitada, requests/ip por minuto e na versão free não vem os dados extras conforme mostrado na pagina inicial.

**Comment by DevMatheusMartinez** [comment]
e como eu recebo o token? para poder utilizar.
No meu caso eu quero utilizar no PHP/LARAVEL.

**Comment by 100n0m3** [comment]
44-991559009, me manda um whats, te explico dai como funciona a v2.

**Comment by gledsoneduardo** [comment]
Também gostaria de saber como funciona a V2

**Comment by 100n0m3** [comment]
FAVOR CHAMAR NO TELEGRAM 44-991559009

**Comment by ccolass** [comment]
Boa Tarde, gostei muito do seu API, vou te chamar no seu numero que você deixou nas mensagens acima para conversamos blz
